package DAO;
// Generated 30/05/2016 04:29:33 PM by Hibernate Tools 4.3.1



/**
 * Presta generated by hbm2java
 */
public class Presta  implements java.io.Serializable {


     private String correo;
     private Articulo articulo;
     private Usuario usuarioByCorreo;
     private Usuario usuarioByCorreoconsumidor;

    public Presta() {
    }

	
    public Presta(Articulo articulo, Usuario usuarioByCorreo) {
        this.articulo = articulo;
        this.usuarioByCorreo = usuarioByCorreo;
    }
    public Presta(Articulo articulo, Usuario usuarioByCorreo, Usuario usuarioByCorreoconsumidor) {
       this.articulo = articulo;
       this.usuarioByCorreo = usuarioByCorreo;
       this.usuarioByCorreoconsumidor = usuarioByCorreoconsumidor;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Usuario getUsuarioByCorreo() {
        return this.usuarioByCorreo;
    }
    
    public void setUsuarioByCorreo(Usuario usuarioByCorreo) {
        this.usuarioByCorreo = usuarioByCorreo;
    }
    public Usuario getUsuarioByCorreoconsumidor() {
        return this.usuarioByCorreoconsumidor;
    }
    
    public void setUsuarioByCorreoconsumidor(Usuario usuarioByCorreoconsumidor) {
        this.usuarioByCorreoconsumidor = usuarioByCorreoconsumidor;
    }




}


