package DAO;
// Generated 30/05/2016 04:29:33 PM by Hibernate Tools 4.3.1



/**
 * Solicita generated by hbm2java
 */
public class Solicita  implements java.io.Serializable {


     private String correo;
     private Articulo articulo;
     private Usuario usuarioByCorreo;
     private Usuario usuarioByCorreosolicita;

    public Solicita() {
    }

    public Solicita(Articulo articulo, Usuario usuarioByCorreo, Usuario usuarioByCorreosolicita) {
       this.articulo = articulo;
       this.usuarioByCorreo = usuarioByCorreo;
       this.usuarioByCorreosolicita = usuarioByCorreosolicita;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Usuario getUsuarioByCorreo() {
        return this.usuarioByCorreo;
    }
    
    public void setUsuarioByCorreo(Usuario usuarioByCorreo) {
        this.usuarioByCorreo = usuarioByCorreo;
    }
    public Usuario getUsuarioByCorreosolicita() {
        return this.usuarioByCorreosolicita;
    }
    
    public void setUsuarioByCorreosolicita(Usuario usuarioByCorreosolicita) {
        this.usuarioByCorreosolicita = usuarioByCorreosolicita;
    }




}


